CREATE TABLE person (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    company VARCHAR NOT NULL,
    email VARCHAR UNIQUE,
    hash VARCHAR NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE NOT NULL
);