<<// Liste routes api //
###
// affiche l'id, le nom, l'heure d'ouverture, l'heure de fermeture, l'adresse et le nombre de places de tous les parkings
GET  https://03e3-193-190-65-64.eu.ngrok.io/parking

###
// idem mais uniquement pour les parkings qui ont leur nom ou leur adresse qui correspondent à la recherche
GET  https://03e3-193-190-65-64.eu.ngrok.io/parking/mag
###
// Liste des utilisateurs
GET  https://03e3-193-190-65-64.eu.ngrok.io/NumberCars
###
//Nombre de places disponibles
GET  https://03e3-193-190-65-64.eu.ngrok.io/AvailablePlace

