<<// Liste routes api //
###
GET http://localhost:8080/parking
// affiche l'id, le nom, l'heure d'ouverture, l'heure de fermeture, l'adresse et le nombre de places de tous les parkings
###
GET http://localhost:8080/parking/mag
// idem mais uniquement pour les parkings qui ont leur nom ou leur adresse qui correspondent à la recherche